# Лабораторная работа 3
- Выполнил: **Савчук Д.И.**
- Группа: **М8О-103М-20**
- Дата сдачи: **07.11.2020**

1. Импортируем **NumPy** под именем **np**

In [1]:
import numpy as np

2. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [2]:
V = np.array([1,2,3,4,5])
n = 3
V0 = np.zeros(len(V) + (len(V)-1)*(n))
print(V)
print(V0)
V0[::n+1] = V
print(V0)

[1 2 3 4 5]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


3. Поменять 2 строки в матрице

In [3]:
A = np.arange(1,10).reshape(3,3)
print('Original array:')
print(A)

A[[0,2]] = A[[2,0]]
print('Modified array:')
print(A)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Modified array:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


4. Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники

In [4]:
tr = np.random.randint(0,100,size=(10,3))
M = np.roll(tr.repeat(2,axis=1),-1,axis=1)
M = np.sort(M.reshape(len(M)*3,2),axis=1)
Z = M.view(dtype=[('p0', int),('p1', int)])
Z = np.unique(Z)
print(Z)

[( 1, 47) ( 1, 93) ( 3, 60) ( 3, 63) (13, 20) (13, 57) (14, 34) (14, 75)
 (15, 37) (15, 82) (16, 36) (16, 60) (20, 41) (20, 57) (20, 93) (21, 32)
 (21, 52) (32, 52) (34, 75) (35, 48) (35, 81) (36, 60) (37, 82) (41, 93)
 (47, 93) (48, 81) (54, 59) (54, 92) (59, 92) (60, 63)]


5. Дан массив C; создать массив A, что np.bincount(A) == C

In [5]:
C = np.bincount(np.random.randint(10, size=(10,)))
print('C =', C)
A = np.repeat(np.arange(len(C)), C)
print('A =', A)
print('np.bincount(A) =', np.bincount(A))
equal = np.allclose(C, np.bincount(A))
print(equal)

C = [2 1 0 1 0 1 0 2 1 2]
A = [0 0 1 3 5 7 7 8 9 9]
np.bincount(A) = [2 1 0 1 0 1 0 2 1 2]
True


6. Посчитать среднее, используя плавающее окно

In [6]:
V = np.arange(10)
print('V =', V)
n = 5

temp = np.cumsum(V, dtype=float)
print('Cumulative sum =', temp)
temp[n:] = temp[n:] - temp[:-n]
M = temp[n - 1:] / n

print('SMA =', M)

V = [0 1 2 3 4 5 6 7 8 9]
Cumulative sum = [ 0.  1.  3.  6. 10. 15. 21. 28. 36. 45.]
SMA = [2. 3. 4. 5. 6. 7.]


7. Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))

In [7]:
n = 4
k = 0
Z = np.arange(10)
print('Z =', Z)
M = np.empty((n, 3))

for i in range(n):
    M[i] = np.array([Z[k], Z[k+1], Z[k+2]])
    k -= 1

print('Array:')
print(M)

Z = [0 1 2 3 4 5 6 7 8 9]
Array:
[[0. 1. 2.]
 [9. 0. 1.]
 [8. 9. 0.]
 [7. 8. 9.]]


8. Инвертировать булево значение, или поменять знак у числового массива без создания нового

In [8]:
V = np.random.randint(0,2,10)
print('V =', V)
V = np.logical_not(V, out=V)
print('-V =', V)

V = np.random.randint(-10,10,10)
print('V =', V)
V = np.negative(V)
print('-V =', V)

V = [1 0 0 0 0 1 1 1 1 0]
-V = [0 1 1 1 1 0 0 0 0 1]
V = [  7   4 -10   8  -2   3  -8  -2   7   0]
-V = [-7 -4 10 -8  2 -3  8  2 -7  0]


9. Посчитать ранг матрицы

In [9]:
M = np.eye(4)
print('Array:')
print(M)
rank = np.linalg.matrix_rank(M)
print('Rank =', rank)

Array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Rank = 4


10. Найти наиболее частое значение в массиве

In [10]:
V = np.random.randint(0,10,20)
print('V =', V)
print('Number =', np.argmax(np.bincount(V)))

V = [1 1 0 3 3 1 3 3 2 1 5 1 3 4 4 1 6 1 5 9]
Number = 1


11. Извлечь все смежные 3x3 блоки из 10x10 матрицы

In [11]:
from numpy.lib import stride_tricks

M = np.random.randint(0,10,(10,10))
print('Original array:')
print(M)
n = 3
i = 1 + np.shape(M)[0] - n
j = 1 + np.shape(M)[1] - n
C = stride_tricks.as_strided(M, shape=(i, j, n, n), strides=M.strides + M.strides, writeable=False)
print('\n3x3:\n', C)

Original array:
[[9 8 3 2 5 1 3 0 1 6]
 [0 5 9 2 1 0 9 4 4 8]
 [2 6 8 7 0 3 6 4 5 1]
 [9 9 8 8 5 8 6 9 2 2]
 [7 8 7 0 6 9 1 7 5 9]
 [6 4 2 9 5 1 8 8 0 5]
 [3 2 4 2 3 8 3 4 9 0]
 [0 5 9 1 4 5 5 6 2 8]
 [6 8 7 6 8 9 3 9 8 5]
 [1 8 4 1 7 6 5 4 3 0]]

3x3:
 [[[[9 8 3]
   [0 5 9]
   [2 6 8]]

  [[8 3 2]
   [5 9 2]
   [6 8 7]]

  [[3 2 5]
   [9 2 1]
   [8 7 0]]

  [[2 5 1]
   [2 1 0]
   [7 0 3]]

  [[5 1 3]
   [1 0 9]
   [0 3 6]]

  [[1 3 0]
   [0 9 4]
   [3 6 4]]

  [[3 0 1]
   [9 4 4]
   [6 4 5]]

  [[0 1 6]
   [4 4 8]
   [4 5 1]]]


 [[[0 5 9]
   [2 6 8]
   [9 9 8]]

  [[5 9 2]
   [6 8 7]
   [9 8 8]]

  [[9 2 1]
   [8 7 0]
   [8 8 5]]

  [[2 1 0]
   [7 0 3]
   [8 5 8]]

  [[1 0 9]
   [0 3 6]
   [5 8 6]]

  [[0 9 4]
   [3 6 4]
   [8 6 9]]

  [[9 4 4]
   [6 4 5]
   [6 9 2]]

  [[4 4 8]
   [4 5 1]
   [9 2 2]]]


 [[[2 6 8]
   [9 9 8]
   [7 8 7]]

  [[6 8 7]
   [9 8 8]
   [8 7 0]]

  [[8 7 0]
   [8 8 5]
   [7 0 6]]

  [[7 0 3]
   [8 5 8]
   [0 6 9]]

  [[0 3 6]
   [5 8 6]
   [6 9 1]]

  [[3 6

12. Рассмотрим множество матриц (n,n) и множество из *p* векторов (n,1). Посчитать сумму *p* произведений матриц (результат имеет размерность (n,1))

In [12]:
p, n = 5, 5
M = np.ones((p,n,n))
print('M:')
print(M)
V = np.ones((p,n,1))
print('V:')
print(V)
S = M[0].dot(V[0])*n
print('S:')
print(S)

M:
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
V:
[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]]
S:
[[25.]
 [25.]
 [25.]
 [25.]
 [25.]]


13. Дан массив 16x16, посчитать сумму по блокам 4x4

In [13]:
M = np.ones((16,16))
print('Array:\n', M)
k = 4
S = np.add.reduceat(np.add.reduceat(M, np.arange(0, M.shape[0], k), axis=0),
                                       np.arange(0, M.shape[1], k), axis=1)
print('Result:\n', S)

Array:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Result:
 [[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


14. Найти n наибольших значений в массиве

In [14]:
V = np.random.randint(0, 100, size=(25,))
print('V =', V)
n = 5

print('Max {} numbers = {}'.format(n, np.sort(V)[25-n:]))

V = [95 66 37 43 29 81  3 71 78 55 72 30 63 44 58  8 24 48 23 45  5 95 75 22
 72]
Max 5 numbers = [75 78 81 95 95]


15. Построить прямое произведение массивов (все комбинации с каждым элементом)

In [15]:
V = np.array([[1, 2, 3], [4, 5], [6, 7]], dtype=object)

A = [np.asarray(a) for a in V]
shape = map(len, A)

i = np.indices(shape, dtype=int)
i = i.reshape(len(A), -1).T

for n in range(len(A)):
    i[:, n] = A[n][i[:, n]]
    
print(i)

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


16. Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [16]:
A = np.random.randint(0,10,(8,3))
B = np.random.randint(0,10,(2,2))
print('Array A:\n', A)
print('Array B:\n', B)


filter_arr = []
for k in range(np.shape(A)[1]-1):
    for i in A[k]:
        if i in B[0] or i in B[1]:
            filter_arr.append(True)
        else:
            filter_arr.append(False)
        
rows = np.nonzero(filter_arr)[0]
print('Result:\n', rows)

Array A:
 [[6 4 4]
 [4 6 2]
 [3 3 6]
 [3 9 2]
 [3 2 3]
 [1 8 7]
 [1 3 4]
 [1 0 7]]
Array B:
 [[0 8]
 [7 9]]
Result:
 []


17. Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

In [17]:
Z = np.random.randint(0,3,(10,3))
print('Original array:\n', Z)

filter_arr = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
print('Modified array:\n', Z[~filter_arr])

Original array:
 [[0 1 2]
 [1 2 0]
 [1 2 1]
 [0 1 2]
 [1 1 0]
 [0 2 2]
 [2 2 0]
 [1 1 0]
 [2 0 2]
 [1 0 0]]
Modified array:
 [[0 1 2]
 [1 2 0]
 [1 2 1]
 [0 1 2]
 [1 1 0]
 [0 2 2]
 [2 2 0]
 [1 1 0]
 [2 0 2]
 [1 0 0]]


18. Преобразовать вектор чисел в матрицу бинарных представлений

In [18]:
V = np.random.randint(32, size=(10, ), dtype=np.uint8).reshape(10, 1)
print('Input:\n', V)
print('Output:\n', np.unpackbits(V, axis=1))

Input:
 [[ 4]
 [ 6]
 [27]
 [ 1]
 [25]
 [ 7]
 [21]
 [19]
 [19]
 [ 4]]
Output:
 [[0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 1 0]
 [0 0 0 1 1 0 1 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 1 1 0 0 1]
 [0 0 0 0 0 1 1 1]
 [0 0 0 1 0 1 0 1]
 [0 0 0 1 0 0 1 1]
 [0 0 0 1 0 0 1 1]
 [0 0 0 0 0 1 0 0]]


19. Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

In [19]:
A = np.arange(5)
B = np.arange(5,10)
print('A =', A)
print('B =', B)

print("np.sum(A) = {}; np.einsum('i->', A) = {}".format(np.sum(A), np.einsum('i->', A)))
print("A * B = {}; np.einsum('i,i->i', A, B) = {}".format(A * B, np.einsum('i,i->i', A, B)))
print("np.inner(A, B) = {}; np.einsum('i,i', A, B) = {}".format(np.inner(A, B), np.einsum('i,i', A, B)))

print('\nnp.outer(A, B):\n', np.outer(A, B))
print("np.einsum('i,j', A, B):\n", np.einsum('i,j', A, B))

A = [0 1 2 3 4]
B = [5 6 7 8 9]
np.sum(A) = 10; np.einsum('i->', A) = 10
A * B = [ 0  6 14 24 36]; np.einsum('i,i->i', A, B) = [ 0  6 14 24 36]
np.inner(A, B) = 80; np.einsum('i,i', A, B) = 80

np.outer(A, B):
 [[ 0  0  0  0  0]
 [ 5  6  7  8  9]
 [10 12 14 16 18]
 [15 18 21 24 27]
 [20 24 28 32 36]]
np.einsum('i,j', A, B):
 [[ 0  0  0  0  0]
 [ 5  6  7  8  9]
 [10 12 14 16 18]
 [15 18 21 24 27]
 [20 24 28 32 36]]
