# Лабораторная работа 1
- Выполнил: **Савчук Д.И.**
- Группа: **М8О-103М-20**
- GitHub: https://github.com/SavchukDI

1. Импортируем **NumPy** под именем **np**

In [1]:
import numpy as np

2. Напечатать версию и конфигурацию

In [2]:
import sys

print(f"Вы используете: Python {sys.version_info.major}.{sys.version_info.minor}.")
print(np.__version__)

Вы используете: Python 3.7.
1.19.1


3. Создать вектор (одномерный массив) размера 10, заполненный нулями

In [3]:
V = np.zeros([10])

print(V)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. Создать вектор размера 10, заполненный единицами

In [4]:
V = np.ones([10])

print(V)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


5. Создать вектор размера 10, заполненный числом 2.5

In [5]:
V = np.array([2.5]*10)

print(V)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


6. Получение документации о функции numpy.add из командной строки

In [6]:
#help(np.add)

7. Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [7]:
V = np.zeros([10])
V[4] = 1

print(V)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


8. Создать вектор со значениями от 10 до 49

In [8]:
V = np.arange(10,50,1)

print(V)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


9. Развернуть вектор (первый становится последним)

In [9]:
V = V[::-1]

print(V)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


10. Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [10]:
M = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


11. Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [11]:
V = np.array([1, 2, 0, 0, 4, 0])

x = np.where(V != 0)

print(np.nonzero(V)[0])
print(x[0])

[0 1 4]
[0 1 4]


12. Создать массив 3x3x3 со случайными значениями

In [12]:
from numpy import random

x = random.randint(100, size=(3, 3, 3))

print(x)

[[[ 6 77 51]
  [88 51 97]
  [70  7 11]]

 [[27 85 99]
  [18 19 72]
  [26  5 61]]

 [[52 34 69]
  [53 90 25]
  [95 48 98]]]


13. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [13]:
x = random.randint(100, size=(10,10))

print(x)
print(f'\nmin = {np.min(x)}, max = {np.max(x)}')

[[21 31 26 22 14 35 51 54 45 26]
 [92 72 35 55 65 62 11 31  9 57]
 [25  2 39 57 71 81 28 74 97 69]
 [76 50 74 90 45 81 45 12 43 96]
 [45 94 20 53 89 91 80 89 64 30]
 [30 48 41 74 38 26 62 70 78 12]
 [67 36 34 57 31 44 31 94 25 97]
 [44 72 89 57 16 43 15 35 68 42]
 [12 71 60 12 33 10  3  1 90 86]
 [51 86 59  3 19 54 40 48 74 16]]

min = 1, max = 97


14. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [14]:
V = random.randint(100, size=(30,))

print(np.mean(V))

50.93333333333333


15. Создать матрицу с 0 внутри, и 1 на границах

In [15]:
M = np.array([[1., 1., 1.], [1., 0, 1.], [1., 1., 1.]])

print(M)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


16. Выяснить результат следующих выражений

In [16]:
0 * np.nan

nan

In [17]:
np.nan == np.nan

False

In [18]:
np.inf > np.nan

False

In [19]:
np.nan - np.nan

nan

17. Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [20]:
M = random.randint(10, size=(5,5))
M[4] = [1, 2, 3, 4, 1]

print(M)

[[1 5 0 7 9]
 [8 3 5 8 8]
 [5 4 6 4 9]
 [1 9 8 8 6]
 [1 2 3 4 1]]


18. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [21]:
O = np.ones([8, 8])
Z = np.zeros([8, 8])
x1 = np.empty([8, 8])

# First method
for i in range(len(O)):
    for j in range(len(O[i])):
        if i % 2 == 0:
            if j % 2 == 0:
                x1[i][j] = 1
            else:
                x1[i][j] = 0
        else:
            if j % 2 == 0:
                x1[i][j] = 0
            else:
                x1[i][j] = 1

print(x1)
print()
        
# Second method
cond = [[True, False, True, False, True, False, True, False],
        [False, True, False, True, False, True, False, True],
        [True, False, True, False, True, False, True, False],
        [False, True, False, True, False, True, False, True],
        [True, False, True, False, True, False, True, False],
        [False, True, False, True, False, True, False, True],
        [True, False, True, False, True, False, True, False],
        [False, True, False, True, False, True, False, True]]

x2 = np.where(cond, O, Z)

print(x2)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


19. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [22]:
x = random.randint(100, size=(6, 7, 8))
n = 0

for i in range(len(x)):
    for j in range(len(x[0])):
        for k in range(len(x[0][0])):
            n += 1
            
            if n == 100:
                print(i,j,k)
                print('x =', x[i][j][k])

#print(x)

1 5 3
x = 51


20. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [23]:
x = np.array([1., 0.])
   
x = np.row_stack((np.tile(x, 4), np.tile(x[::-1], 4)))
x = np.row_stack((np.row_stack((x, x)), np.row_stack((x, x))))

print(x)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
