# Лабораторная работа 1
- Выполнил: **Савчук Д.И.**
- Группа: **М8О-103М-20**
- Дата сдачи: **17.10.20**

1. Импортируем **NumPy** под именем **np**

In [1]:
import numpy as np

2. Напечатать версию и конфигурацию

In [2]:
import sys

print(f"Вы используете: Python {sys.version_info.major}.{sys.version_info.minor}.")
print(f"Вы используете: NumPy {np.__version__}")

Вы используете: Python 3.7.
Вы используете: NumPy 1.19.1


3. Создать вектор (одномерный массив) размера 10, заполненный нулями

In [3]:
V = np.zeros([10])

print(V)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. Создать вектор размера 10, заполненный единицами

In [4]:
V = np.ones([10])

print(V)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


5. Создать вектор размера 10, заполненный числом 2.5

In [5]:
V = np.array([2.5]*10)

print(V)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


6. Получение документации о функции numpy.add из командной строки

In [6]:
#help(np.add)

7. Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [7]:
V = np.zeros([10])
V[4] = 1

print(V)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


8. Создать вектор со значениями от 10 до 49

In [8]:
V = np.arange(10,50,1)

print(V)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


9. Развернуть вектор (первый становится последним)

In [9]:
V = V[::-1]

print(V)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


10. Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [10]:
M = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


11. Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [11]:
V = np.array([1, 2, 0, 0, 4, 0])

x = np.where(V != 0)

print(np.nonzero(V))
print(x)

(array([0, 1, 4], dtype=int64),)
(array([0, 1, 4], dtype=int64),)


12. Создать массив 3x3x3 со случайными значениями

In [12]:
from numpy import random

x = random.randint(100, size=(3, 3, 3))

print(x)

[[[82 46  8]
  [36 24 26]
  [79 12 17]]

 [[56 21 38]
  [28 99 51]
  [68 42 73]]

 [[18 65 37]
  [48 61 22]
  [95 67 86]]]


13. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [13]:
x = random.randint(100, size=(10,10))

print(x)
print(f'\nmin = {np.min(x)}, max = {np.max(x)}')

[[56 27 57 62 86 98 81 95 54 21]
 [91 62 93 96 96 83 44  5 33 55]
 [57  5 44 79 91 95  5 37 13 20]
 [44 96 61 92 53 13 94 36 72 36]
 [17 92 73 42 29 74 82 66 93 12]
 [37 26  9 79 60 26 86 33  9 14]
 [21 76 31 52 46 42 96 59 70 17]
 [73 76 61 33 37  1 27 24 59 61]
 [34 71 40 46 38 37 47 20 39 74]
 [65 59 82  0 76 96 10 61 48 28]]

min = 0, max = 98


14. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [14]:
V = random.randint(100, size=(30,))

print(np.mean(V))

46.63333333333333


15. Создать матрицу с 0 внутри, и 1 на границах

In [15]:
M = np.array([[1., 1., 1.], [1., 0, 1.], [1., 1., 1.]])

print(M)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


16. Выяснить результат следующих выражений

In [16]:
0 * np.nan

nan

In [17]:
np.nan == np.nan

False

In [18]:
np.inf > np.nan

False

In [19]:
np.nan - np.nan

nan

17. Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [20]:
M = random.randint(10, size=(5,5))
    
M[1][0] = 1
M[2][1] = 2
M[3][2] = 3
M[4][3] = 4

print(M)

[[2 6 2 0 6]
 [1 7 4 3 8]
 [9 2 3 5 6]
 [9 1 3 0 3]
 [9 1 8 4 4]]


18. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [21]:
O = np.ones([8, 8])
Z = np.zeros([8, 8])
x1 = np.empty([8, 8])

# First method
for i in range(len(O)):
    for j in range(len(O[i])):
        if i % 2 == 0:
            if j % 2 == 0:
                x1[i][j] = 1
            else:
                x1[i][j] = 0
        else:
            if j % 2 == 0:
                x1[i][j] = 0
            else:
                x1[i][j] = 1

print(x1)
print()
        
# Second method
cond = [[True, False, True, False, True, False, True, False],
        [False, True, False, True, False, True, False, True],
        [True, False, True, False, True, False, True, False],
        [False, True, False, True, False, True, False, True],
        [True, False, True, False, True, False, True, False],
        [False, True, False, True, False, True, False, True],
        [True, False, True, False, True, False, True, False],
        [False, True, False, True, False, True, False, True]]

x2 = np.where(cond, O, Z)

print(x2)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


19. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [22]:
x = random.randint(100, size=(6, 7, 8))
n = 0

for i in range(len(x)):
    for j in range(len(x[0])):
        for k in range(len(x[0][0])):
            n += 1
            
            if n == 100:
                print(i,j,k)
                print('x =', x[i][j][k])

#print(x)

1 5 3
x = 53


20. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [23]:
x = np.array([1., 0.])
   
x = np.row_stack((np.tile(x, 4), np.tile(x[::-1], 4)))
x = np.row_stack((np.row_stack((x, x)), np.row_stack((x, x))))

print(x)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
